up:
	docker-compose -f ./build/docker-compose.yml up -d

# Bring down the services
# Use -v to remove volumes if needed (optional)
down:
	docker-compose -f ./build/docker-compose.yml down

build-app:
	docker-compose -f ./build/docker-compose.yml build